Shiny helm chart: Fix for "upgrade failed expected string got bool"
I'm see this error in Jenkins and it's likely caused by the fact that
the `AuthProxy.AuthenticationRequired` value is `true` (boolean) instead of
`"true"` (string)

Error:

    Error: UPGRADE FAILED: error validating "": error validating data: expected type string, for field spec.template.spec.containers[0].env[7].value, got bool